# Useful data passing to index via template

degreeList = {
    "1602": "Diploma in Languages",
    # "2000": "Arts",
    "2007": "Agribusiness",
    "2031": "Science (Honours)",
    "2033": "Social Science (Honours)",
    "2040": "Journalism",
    "2041": "Journalism (Honours)",
    # "2052": "Arts (Honours)",
    "2063": "Regional and Town Planning",
    # "2066": "Arts / Education (Secondary)",
    # "2102": "Journalism / Arts",
    "2129": "Business Management (Honours)",
    "2131": "Commerce (Honours)",
    "2132": "Economics (Honours)",
    "2139": "Advanced Business (Honours)",
    "2140": "Advanced Finance and Economics (Honours)",
    # "2142": "Arts / Laws (Honours)",
    "2171": "Business Management",
    # "2175": "Business Management / Arts",
    "2180": " of Business Management / Commerce",
    "2181": "Business Management / Economics",
    "2235": "Information Technology (Honours)",
    "2237": "Communication (Honours)",
    "2241": "Nursing",
    "2243": "Nursing (Honours)",
    "2252": "Health Sciences",
    "2253": "Health Sciences (Honours)",
    "2261": "Midwifery",
    "2264": "Human Services (Honours)",
    "2266": "Midwifery (Honours)",
    "2290": "Nursing / Midwifery",
    "2293": "Architectural Design",
    "2298": "Business Management / Education (Secondary)",
    "2299": "Business Management / Information Technology",
    "2306": "Education (Primary)",
    "2312": "Education (Secondary)",
    "2316": "International Studies",
    "2317": "International Studies (Honours)",
    "2320": "Diploma in Arts",
    "2334": "Business Management / Laws (Honours)",
    "2335": "Business Management / Science",
    "2336": "Commerce",
    # "2337": "Commerce / Arts",
    "2338": "Commerce / Economics",
    "2339": "Commerce / Information Technology",
    "2350": "Engineering (Honours) and Master of Engineering",
    "2354": "Science (Honours) - Gatton",
    "2355": "Music (Honours)",
    "2357": "Music (Honours) / Education (Secondary)",
    "2367": "Dental Science (Honours)",
    "2368": "Occupational Therapy (Honours)",
    "2369": "Physiotherapy (Honours)",
    "2370": "Speech Pathology (Honours)",
    "2371": "Exercise and Sport Sciences (Honours)",
    "2372": "Health, Sport and Physical Education (Honours)",
    "2373": "Pharmacy (Honours)",
    "2376": "Environmental Management (Honours)",
    "2378": "Veterinary Science (Honours)",
    "2379": "Psychological Science (Honours)",
    "2380": "Education (Primary) (Honours)",
    "2381": "Regional and Town Planning (Honours)",
    "2382": "Social Work (Honours)",
    "2387": "Veterinary Technology",
    "2388": "Wildlife Science",
    "2392": "Agribusiness / Wildlife Science",
    # "2405": "Music (Honours) / Arts",
    "2413": "Clinical Exercise Physiology (Honours)",
    "2414": "Advanced Humanities (Honours)",
    "2415": "Biomedical Science",
    "2417": "Equine Science (Honours)",
    "2419": "Wildlife Science (Honours)",
    "2421": "Mathematics (Honours)",
    "2422": "Veterinary Technology (Honours)",
    "2423": "Biomedical Science (Honours)",
    "2448": "Agricultural Science",
    "2449": "Agribusiness / Agricultural Science",
    "2450": "Agricultural Science (Honours)",
    "2451": "Computer Science",
    "2452": "Computer Science (Honours)",
    "2453": "Information Technology",
    "2454": "Design",
    "2455": "Engineering (Honours)",
    "2456": "Biotechnology",
    "2457": "Biotechnology (Honours)",
    "2458": "Environmental Science",
    "2459": "Environmental Science (Honours)",
    "2460": "Mathematics",
    "2461": "Science",
    "2463": "Computer Science / Business Management",
    "2464": "Computer Science / Commerce",
    "2465": "Commerce / Laws (Honours)",
    "2466": "Commerce / Science",
    "2467": "Economics",
    # "2468": "Economics / Arts",
    "2469": "Economics / Laws (Honours)",
    "2470": "Economics / Science",
    "2471": "Laws (Honours)",
    "2472": "Science / Laws (Honours)",
    "2473": "Tourism, Hospitality and Event Management",
    # "2474": "Arts / Tourism, Hospitality and Event Management",
    "2475": "Business Management / Tourism, Hospitality and Event Management",
    "2476": "Diploma in Science",
    "2477": "Biomedical Science / Science",
    # "2478": "Science / Arts",
    "2479": "Science / Education (Secondary)",
    "2480": "Computer Science / Laws (Honours)",
    "2481": "Computer Science / Master of Cyber Security",
    "2482": "Computer Science / Master of Data Science",
    # "2483": "Computer Science / Arts",
    "2484": "Computer Science / Science",
    # "2485": "Engineering (Honours) / Arts",
    "2486": "Engineering (Honours) / Biotechnology",
    "2487": "Engineering (Honours) / Business Management",
    "2488": "Engineering (Honours) / Commerce",
    "2489": "Engineering (Honours) / Computer Science",
    "2490": "Engineering (Honours) / Economics",
    "2491": "Engineering (Honours) / Information Technology",
    "2492": "Engineering (Honours) / Mathematics",
    "2493": "Engineering (Honours) / Science",
    # "2494": "Information Technology / Arts",
    "2495": "Information Technology / Science",
    "2496": "Science / Journalism",
    "2497": "Mathematics / Computer Science",
    "2498": "Mathematics / Economics",
    "2499": "Mathematics / Commerce",
    "2500": "Mathematics / Business Management",
    "2501": "Mathematics / Education (Secondary)",
    "2502": "Mathematics / Science",
    # "2503": "Mathematics / Arts",
    # "2504": "Communication / Arts",
    # "2505": "Arts / Social Science",
    "2506": "Social Science",
    "2507": "Communication",
    "2508": "Communication / Journalism",
    "2509": "Business Management / Communication",
    "2510": "Business Management / Journalism",
    "2511": "Humanities / Laws (Honours)",
    "2512": "Journalism / Laws (Honours)",
    "2514": "Music (Honours) / Science",
    "2515": "Engineering (Honours) / Design",
    "2516": "Advanced Science (Honours)",
    "2517": "Business Management / Design",
    "2519": "Criminology and Criminal Justice",
    # "2521": "Criminology and Criminal Justice/Arts",
    "2522": "Politics, Philosophy and Economics (Honours)",
    "2524": "Computer Science / Economics",
    "2525": "Human Movement and Nutrition Sciences",
    # "2526": "Human Movement and Nutrition Sciences / Arts",
    "2527": "Human Movement and Nutrition Sciences / Business Management",
    "2528": "Human Movement & Nutrition Sci/Tourism, Hospitality & Event Mgmt",
    "2529": "Human Movement and Nutrition Sciences / Journalism",
    "2530": "Human Movement and Nutrition Sciences (Honours)",
    "2531": "Information Technology/Design"
}
